### PR TITLE
#377 access control expose headers

### LINKED ISSUE #377: Support for `Access-Control-Expose-Headers`
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers

I first happened across this one when working with Taffy's Etag feature in my Javascript client implementation. Custom headers added using `withHeaders` suffer a similar problem.

I would propose that if Etag is enabled and/or any custom headers are present, to include those keys inside an `Access-Control-Expose-Headers` response header within `onRequest` (after the Etag check)

### PR DESCRIPTION
**Pull request by timmixell**
Resolves #377 

@atuttle this is all i was envisioning for this one. i'm not 100% what you mean re: config and/or metadata, but i figured you could furnish additional feedback against the PR.

thanks!

### CODE REVIEW

**Comment by pfreitag** [comment]
@timmixell would it be possible to include a test case for this so we can be sure it is working and doesn't get broken in the future?

**Comment by timmixell** [comment]
@pfreitag per my original comment, I was hoping the proposed changes would solicit some feedback around the additions (either a 👍 or 👎 ). I'll add a test case ASAP.

**Comment by timmixell** [comment]
@pfreitag sorry for delay in unit tests on this one. should be good to go now.

**Comment by atuttle** [comment]
Please add documentation for this new configuration option. As in #381 you should assume this will be part of version 3.3.0.

**Comment by timmixell** [comment]
Please 👀 at your convenience: https://github.com/atuttle/TaffyDocs/pull/19

Thanks!

**Pull request merged**
