### PR TITLE
Filled out box.json

### PR DESCRIPTION
**Pull request by KamasamaK**
Filled out `box.json` to improve the experience when using the repository as a dependency endpoint with CommandBox. This could also be used to publish to ForgeBox if the interest arises (and ownership is transferred).

* Ignores files that are unnecessary for deployment
* Lowercased slug so that default installation folder matches docs
* Other changes that would really only matter for ForgeBox
* Formatting

### CODE REVIEW

**Comment by KamasamaK** [comment]
@pfreitag Since it looks like you setup the CI, do you have any insight on why this is failing?

**Comment by pfreitag** [comment]
@KamasamaK - I am looking into it, it looks like it is an issue with commandbox running recipes the `server start` is getting ignored causing the Travis-CI script to fail.

**Comment by pfreitag** [comment]
ok I have a fix for Travis-CI in #388

**Comment by KamasamaK** [comment]
@atuttle Do you have any feedback on this?

**Comment by atuttle** [comment]
I don't use ForgeBox but this looks decent enough to me. I guess if there are any bugs we'll find out soon enough. :)

**Pull request merged**
