### PR TITLE
Fix for OpenBD compatibility regarding determining Query column names

### PR DESCRIPTION
**Pull request by alexskinner**
OpenBD can use the same method as railo for determining column names, modded the resource.cfc to allow OpenBD to use the same logic as Railo and ColdFusion server to use the other method

### CODE REVIEW

**Comment by alexskinner** [comment]
Actually first time i've done a pull request using Github missed the vital step it seems of branching per fix so i could isolate the two changes i've done into seperate requests. How's best to proceed ?

**Comment by atuttle** [comment]
Thanks for the PR(s) Alex. If you'd like to swap over to another branch, you can create the new branch, cherry-pick the commit(s) you want in it, and then close this PR.

**Comment by alexskinner** [comment]
Yeah I guess I'd need to reclone right or branch before I made the changes.
Leave it with me I don't use github much

A

**Comment by atuttle** [comment]
You can create a branch from an older commit. If you're on the command line it's as easy as: `git branch <branchname> <sha>`. That doesn't switch you to the new branch, though, so follow that with a `git checkout <branchname>`. Then cherry-pick the commits you want: `git cherry-pick <sha>` will copy it to the current branch. After cherry-picking, you can revert them in your master branch, too.

**Comment by alexskinner** [comment]
Haha I thought when you said cherry pick,  Sure if you know git.  But that
helps ta

**Comment by pfreitag** [comment]
@alexskinner this PR is old and now has conflicts, are you ok with closing this is anyone using OpenBD with Taffy at this point?

**Comment by alexskinner** [comment]
We haven’t for a very long time I’m sure it’s fine to close

Thanks

Alex

**Comment by pfreitag** [comment]
Thanks @alexskinner 

Closing this PR as OpenBD is not officially supported.

**Pull request closed without merging**
